import Head from 'next/head'
import Timer, { TIMES } from '../components/Timer'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Timer {...TIMES["HOURS"]}/>
      <Timer {...TIMES["MINUTES"]}/>
      <Timer {...TIMES["SECONDS"]}/>
      <Timer {...TIMES["MILLISECONDS"]} />
    </div>
  )
}
