import dynamic from 'next/dynamic';
import Head from 'next/head'
import Timer, { TIMES } from '../components/Timer'
import styles from '../styles/Home.module.css'

const ClientOnlyTime = dynamic(() => import("../components/Timer"), {
  ssr: false,
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ClientOnlyTime {...TIMES["HOURS"]}/>
      <ClientOnlyTime {...TIMES["MINUTES"]}/>
      <ClientOnlyTime {...TIMES["SECONDS"]}/>
      <ClientOnlyTime {...TIMES["MILLISECONDS"]} />
    </div>
  )
}
